"""initial schema

Revision ID: 05c800dcab28
Revises: 
Create Date: 2026-04-24 14:51:31.479528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05c800dcab28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('employer_code', sa.String(), nullable=False),
    sa.Column('employer_type', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employer_code')
    )
    op.create_table('leave_types',
    sa.Column('type_code', sa.String(), nullable=False),
    sa.Column('type_label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_code')
    )
    op.create_table('plan_tiers',
    sa.Column('tier_code', sa.String(), nullable=False),
    sa.Column('tier_label', sa.String(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier_code')
    )
    op.create_table('plan_types',
    sa.Column('plan_code', sa.String(), nullable=False),
    sa.Column('plan_label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_code')
    )
    op.create_table('system_configurations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('config_key', sa.String(), nullable=False),
    sa.Column('config_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('superseded_date', sa.Date(), nullable=True),
    sa.Column('set_by', sa.UUID(), nullable=True),
    sa.Column('set_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key', 'effective_date')
    )
    op.create_table('members',
    sa.Column('member_number', sa.String(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('middle_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('suffix', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('ssn_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('ssn_last_four', sa.String(length=4), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('member_status', sa.String(), server_default='active', nullable=False),
    sa.Column('status_date', sa.Date(), nullable=True),
    sa.Column('plan_tier_id', sa.UUID(), nullable=True),
    sa.Column('plan_type_id', sa.UUID(), nullable=True),
    sa.Column('plan_choice_date', sa.Date(), nullable=True),
    sa.Column('plan_choice_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('certification_date', sa.Date(), nullable=True),
    sa.Column('certification_date_source', sa.String(), server_default='calculated', nullable=False),
    sa.Column('certification_date_note', sa.Text(), nullable=True),
    sa.Column('certification_date_set_by', sa.UUID(), nullable=True),
    sa.Column('certification_date_set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_tier_id'], ['plan_tiers.id'], ),
    sa.ForeignKeyConstraint(['plan_type_id'], ['plan_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_number')
    )
    op.create_table('plan_configurations',
    sa.Column('plan_tier_id', sa.UUID(), nullable=False),
    sa.Column('plan_type_id', sa.UUID(), nullable=False),
    sa.Column('employment_type', sa.String(), nullable=False),
    sa.Column('benefit_multiplier', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('fac_years', sa.Integer(), nullable=False),
    sa.Column('vesting_years', sa.Integer(), nullable=False),
    sa.Column('normal_retirement_age', sa.Integer(), nullable=False),
    sa.Column('early_retirement_age', sa.Integer(), nullable=True),
    sa.Column('member_contribution_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('employer_contribution_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('cola_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('cola_cap', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('cola_type', sa.String(), nullable=True),
    sa.Column('sick_time_eligible', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sick_time_conversion_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('superseded_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_tier_id'], ['plan_tiers.id'], ),
    sa.ForeignKeyConstraint(['plan_type_id'], ['plan_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_tier_id', 'plan_type_id', 'employment_type', 'effective_date')
    )
    op.create_table('beneficiaries',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('beneficiary_type', sa.String(), nullable=False),
    sa.Column('share_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ssn_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('ssn_last_four', sa.String(length=4), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employment_records',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('employment_type', sa.String(), nullable=False),
    sa.Column('position_title', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('termination_reason', sa.String(), nullable=True),
    sa.Column('percent_time', sa.Numeric(precision=5, scale=2), server_default='100.00', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('concurrent_employment_group', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_addresses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.String(), nullable=False),
    sa.Column('line1', sa.Text(), nullable=False),
    sa.Column('line2', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=2), server_default='US', nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('contact_type', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_balances',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employment_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('balance_date', sa.Date(), nullable=False),
    sa.Column('balance_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employment_id'], ['employment_records.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employment_id', 'leave_type_id', 'balance_date')
    )
    op.create_table('salary_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employment_id', sa.UUID(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('annual_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('salary_type', sa.String(), server_default='annual', nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employment_id'], ['employment_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_credit_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('employment_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('credit_days', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('credit_years', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('accrual_rule_config_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.UUID(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['accrual_rule_config_id'], ['system_configurations.id'], ),
    sa.ForeignKeyConstraint(['employment_id'], ['employment_records.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_credit_entries')
    op.drop_table('salary_history')
    op.drop_table('leave_balances')
    op.drop_table('member_contacts')
    op.drop_table('member_addresses')
    op.drop_table('employment_records')
    op.drop_table('beneficiaries')
    op.drop_table('plan_configurations')
    op.drop_table('members')
    op.drop_table('system_configurations')
    op.drop_table('plan_types')
    op.drop_table('plan_tiers')
    op.drop_table('leave_types')
    op.drop_table('employers')
    # ### end Alembic commands ###
