"""add_payroll_ingestion_tables

Revision ID: 4abbaab68571
Revises: fff56dc49d99
Create Date: 2026-04-24 21:03:06.396578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4abbaab68571'
down_revision: Union[str, None] = 'fff56dc49d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('source_format', sa.String(), nullable=False),
    sa.Column('source_filename', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('row_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('processed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_report_rows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('payroll_report_id', sa.UUID(), nullable=False),
    sa.Column('member_number', sa.String(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('employment_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('employee_contribution', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('employer_contribution', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('days_worked', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['employment_id'], ['employment_records.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['payroll_report_id'], ['payroll_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contribution_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('employment_id', sa.UUID(), nullable=True),
    sa.Column('payroll_report_row_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('employee_contribution', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('employer_contribution', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contribution_type', sa.String(), server_default='normal', nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.UUID(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employment_id'], ['employment_records.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['payroll_report_row_id'], ['payroll_report_rows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contribution_records')
    op.drop_table('payroll_report_rows')
    op.drop_table('payroll_reports')
    # ### end Alembic commands ###
