"""add retirement_cases

Revision ID: adffc0c6941e
Revises: c3cefdb6ca94
Create Date: 2026-04-28 16:23:38.817459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adffc0c6941e'
down_revision: Union[str, None] = 'c3cefdb6ca94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retirement_cases',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('retirement_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('sick_leave_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('benefit_option_type', sa.String(), server_default='single_life', nullable=False),
    sa.Column('beneficiary_id', sa.UUID(), nullable=True),
    sa.Column('beneficiary_age_at_retirement', sa.Integer(), nullable=True),
    sa.Column('desired_reversionary_monthly', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('calculation_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_monthly_annuity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('first_payment_date', sa.Date(), nullable=True),
    sa.Column('first_payment_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_by', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['first_payment_id'], ['benefit_payments.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retirement_cases')
    # ### end Alembic commands ###
