"""add member_benefit_elections and beneficiary columns on benefit_payments

Revision ID: c3cefdb6ca94
Revises: c909a13fd9f3
Create Date: 2026-04-28 16:16:17.924265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3cefdb6ca94'
down_revision: Union[str, None] = 'c909a13fd9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_benefit_elections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('option_type', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.UUID(), nullable=True),
    sa.Column('beneficiary_age_at_election', sa.Integer(), nullable=True),
    sa.Column('member_monthly_annuity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reversionary_monthly_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('elected_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('benefit_payments', sa.Column('beneficiary_id', sa.UUID(), nullable=True))
    op.add_column('benefit_payments', sa.Column('beneficiary_bank_account_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'benefit_payments', 'beneficiaries', ['beneficiary_id'], ['id'])
    op.create_foreign_key(None, 'benefit_payments', 'beneficiary_bank_accounts', ['beneficiary_bank_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'benefit_payments', type_='foreignkey')
    op.drop_constraint(None, 'benefit_payments', type_='foreignkey')
    op.drop_column('benefit_payments', 'beneficiary_bank_account_id')
    op.drop_column('benefit_payments', 'beneficiary_id')
    op.drop_table('member_benefit_elections')
    # ### end Alembic commands ###
