"""add_payment_type_beneficiary_updates

Revision ID: c909a13fd9f3
Revises: e0d9170ae77e
Create Date: 2026-04-28 14:59:11.470395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c909a13fd9f3'
down_revision: Union[str, None] = 'e0d9170ae77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiary_bank_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('beneficiary_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.Text(), nullable=False),
    sa.Column('routing_number', sa.String(length=9), nullable=False),
    sa.Column('account_number_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('account_last_four', sa.String(length=4), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('beneficiaries', sa.Column('org_name', sa.Text(), nullable=True))
    op.add_column('beneficiaries', sa.Column('linked_member_id', sa.UUID(), nullable=True))
    op.add_column('beneficiaries', sa.Column('is_primary', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('beneficiaries', 'first_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('beneficiaries', 'last_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'beneficiaries', 'members', ['linked_member_id'], ['id'])
    op.add_column('benefit_payments', sa.Column('payment_type', sa.String(), server_default='annuity', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('benefit_payments', 'payment_type')
    op.drop_constraint(None, 'beneficiaries', type_='foreignkey')
    op.alter_column('beneficiaries', 'last_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('beneficiaries', 'first_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('beneficiaries', 'is_primary')
    op.drop_column('beneficiaries', 'linked_member_id')
    op.drop_column('beneficiaries', 'org_name')
    op.drop_table('beneficiary_bank_accounts')
    # ### end Alembic commands ###
